# 测试配置文件 - 请根据你的实际情况修改

[llm]
# 选择你要使用的模型和API
model = "gpt-3.5-turbo"  # 或者 "qwen2:7b", "glm-4" 等
api_key = "your-api-key-here"  # 替换为你的真实API密钥
base_url = "https://api.openai.com/v1/chat/completions"  # 对应的API端点
max_tokens = 4096
temperature = 0.2

[chunking]
chunk_size = 100
overlap = 20

[standardization]
enabled = true
use_llm_for_entities = true

[inference]
enabled = true
use_llm_for_inference = true
apply_transitive = true

[visualization]
edge_smooth = "continuous"
dark_mode = false
node_size = 25
font_size = 14
edge_length = 200
physics_enabled = true
community_detection = true
